// Feed-scheme picker: three cards named for the hardware, with the scheme's
// real schematic line art as card art, generated by the engine renderer from
// a representative synthetic result (so the cards can never drift from the
// canonical drawings). Labels are stripped and the viewBox cropped for
// thumbnail legibility.

import type { DesignResult } from "../../engine/index";
import { FEED_BALUN4, FEED_LINE, renderFeedSchematic } from "../../engine/index";
import { defaultSpec } from "../state/uiSpec";

interface FeedOption {
  token: string;
  name: string;
  tradeoff: string;
  art: string;
}

// A plausible tuned result per feed; only the fields the schematic reads
// matter (spec/feed, z_in for the match section, crossed flag).
function syntheticResult(feed: string, zReal: number): DesignResult {
  return {
    spec: { ...defaultSpec(), feed },
    baseFactor: 1.0518,
    zIn: { re: zReal, im: 0.0 },
    phaseDiffDeg: 89.9,
    loopBalance: 1.05,
    crossedPhasingLine: false,
    sense: "RIGHT",
    arBoresightDb: 1.5,
    arConeWorstDb: 3.8,
    arPeakDb: 1.2,
    coverageGainDb: 1.2,
    deck: "",
    loopAFeedZ: null,
    loopBFeedZ: null,
  };
}

// Padding (in drawing units) kept above and below the content when cropping a
// schematic down to card art.
const CARD_ART_PADDING = 12;

// Vertical extent [minY, maxY] of the drawn geometry, in viewBox units. Bounds
// circles (cy +/- r), lines (y1, y2), and paths -- both their literal
// coordinates and, for the full-circle loop arcs (large-arc flag set), the
// center +/- radius the endpoints alone understate. This is what lets the crop
// track the actual drawing instead of hand-tuned per-feed numbers.
function contentYExtent(svg: string): [number, number] {
  let lo = Number.POSITIVE_INFINITY;
  let hi = Number.NEGATIVE_INFINITY;
  const add = (y: number): void => {
    if (y < lo) lo = y;
    if (y > hi) hi = y;
  };
  for (const m of svg.matchAll(/<circle\b[^>]*?\bcy="([\d.]+)"[^>]*?\br="([\d.]+)"/g)) {
    const cy = Number(m[1]);
    const r = Number(m[2]);
    add(cy - r);
    add(cy + r);
  }
  for (const m of svg.matchAll(/<line\b[^>]*?\by1="([\d.]+)"[^>]*?\by2="([\d.]+)"/g)) {
    add(Number(m[1]));
    add(Number(m[2]));
  }
  for (const m of svg.matchAll(/<path\b[^>]*?\bd="([^"]*)"/g)) {
    const d = m[1] ?? "";
    for (const c of d.matchAll(/[,V]([\d.]+)/g)) {
      add(Number(c[1]));
    }
    // Full-circle loop symbols reach center +/- radius past their gap endpoints.
    const loop = d.match(/M[\d.]+,([\d.]+) A([\d.]+),[\d.]+ 0 1 [01] [\d.]+,([\d.]+)/);
    if (loop) {
      const cy = (Number(loop[1]) + Number(loop[3])) / 2;
      const r = Number(loop[2]);
      add(cy - r);
      add(cy + r);
    }
  }
  return [lo, hi];
}

// Thumbnail treatment: drop the text labels and crop to the drawn content so
// the loops are never clipped, with no per-feed magic numbers.
function cardArt(feed: string, zReal: number): string {
  const svg = renderFeedSchematic(syntheticResult(feed, zReal)).replace(
    /<text[^>]*>[^<]*<\/text>/g,
    "",
  );
  const [lo, hi] = contentYExtent(svg);
  const y = Math.floor(lo - CARD_ART_PADDING);
  const h = Math.ceil(hi - lo + 2 * CARD_ART_PADDING);
  return svg
    .replace(/viewBox="0 0 (\d+) \d+"/, `viewBox="0 ${y} $1 ${h}"`)
    .replace('role="img"', 'role="img" aria-hidden="true"');
}

const LINE_ART = cardArt(FEED_LINE, 45.8);
const BALUN4_ART = cardArt(FEED_BALUN4, 49.6);

const OPTIONS: FeedOption[] = [
  {
    token: FEED_LINE,
    name: "Phasing line",
    tradeoff: "simplest, one coax",
    art: LINE_ART,
  },
  {
    token: FEED_BALUN4,
    name: "4:1 balun",
    tradeoff: "balanced feed (F5VIF)",
    art: BALUN4_ART,
  },
];

export function FeedCards({
  value,
  onChange,
}: {
  value: string;
  onChange: (token: string) => void;
}): JSX.Element {
  return (
    <div className="feedcards" role="radiogroup" aria-label="feed scheme">
      {OPTIONS.map((opt) => (
        <div
          key={opt.token}
          className={`feedcard${opt.token === value ? " on" : ""}`}
          tabIndex={0}
          role="radio"
          aria-checked={opt.token === value}
          onClick={() => onChange(opt.token)}
          onKeyDown={(e) => {
            if (e.key === "Enter" || e.key === " ") {
              e.preventDefault();
              onChange(opt.token);
            }
          }}
        >
          <div className="fc-head">
            <span className="fc-name">{opt.name}</span>
            <span className="fc-tag">
              {opt.token} &middot; {opt.tradeoff}
            </span>
          </div>
          {/* Only the selected scheme shows its art, to keep the section
              compact. Decorative silhouette from our own static markup. */}
          {opt.token === value && <div dangerouslySetInnerHTML={{ __html: opt.art }} />}
        </div>
      ))}
    </div>
  );
}
