// Feed-scheme picker: three cards named for the hardware, with the scheme's
// real schematic line art as card art, generated by the engine renderer from
// a representative synthetic result (so the cards can never drift from the
// canonical drawings). Labels are stripped and the viewBox cropped for
// thumbnail legibility.

import type { DesignResult } from "../../engine/index";
import {
  FEED_BALUN4,
  FEED_LINE,
  FEED_TURNSTILE,
  renderFeedSchematic,
} from "../../engine/index";
import { defaultSpec } from "../state/uiSpec";

interface FeedOption {
  token: string;
  name: string;
  tradeoff: string;
  art: string;
}

// A plausible tuned result per feed; only the fields the schematic reads
// matter (spec/feed, z_in for the match section, crossed flag).
function syntheticResult(feed: string, zReal: number): DesignResult {
  return {
    spec: { ...defaultSpec(), feed },
    baseFactor: 1.0518,
    zIn: { re: zReal, im: 0.0 },
    phaseDiffDeg: 89.9,
    loopBalance: 1.05,
    crossedPhasingLine: false,
    sense: "RIGHT",
    arBoresightDb: 1.5,
    arConeWorstDb: 3.8,
    arPeakDb: 1.2,
    coverageGainDb: 1.2,
    deck: "",
  };
}

// Thumbnail treatment: drop the text labels and crop the label whitespace.
function cardArt(feed: string, zReal: number, cropY: number, cropH: number): string {
  const svg = renderFeedSchematic(syntheticResult(feed, zReal));
  return svg
    .replace(/<text[^>]*>[^<]*<\/text>/g, "")
    .replace(/viewBox="0 0 (\d+) \d+"/, `viewBox="0 ${cropY} $1 ${cropH}"`)
    .replace('role="img"', 'role="img" aria-hidden="true"');
}

const LINE_ART = cardArt(FEED_LINE, 45.8, 100, 200);
const TURNSTILE_ART = cardArt(FEED_TURNSTILE, 25.3, 78, 222);
const BALUN4_ART = cardArt(FEED_BALUN4, 49.6, 102, 200);

const OPTIONS: FeedOption[] = [
  {
    token: FEED_LINE,
    name: "Phasing line",
    tradeoff: "simplest, one coax",
    art: LINE_ART,
  },
  {
    token: FEED_TURNSTILE,
    name: "Turnstile",
    tradeoff: "best current balance",
    art: TURNSTILE_ART,
  },
  {
    token: FEED_BALUN4,
    name: "4:1 balun",
    tradeoff: "balanced feed (F5VIF)",
    art: BALUN4_ART,
  },
];

export function FeedCards({
  value,
  onChange,
}: {
  value: string;
  onChange: (token: string) => void;
}): JSX.Element {
  return (
    <div className="feedcards" role="radiogroup" aria-label="feed scheme">
      {OPTIONS.map((opt) => (
        <div
          key={opt.token}
          className={`feedcard${opt.token === value ? " on" : ""}`}
          tabIndex={0}
          role="radio"
          aria-checked={opt.token === value}
          onClick={() => onChange(opt.token)}
          onKeyDown={(e) => {
            if (e.key === "Enter" || e.key === " ") {
              e.preventDefault();
              onChange(opt.token);
            }
          }}
        >
          <div className="fc-head">
            <span className="fc-name">{opt.name}</span>
            <span className="fc-tag">
              {opt.token} &middot; {opt.tradeoff}
            </span>
          </div>
          {/* Decorative silhouette from our own static markup. */}
          <div dangerouslySetInnerHTML={{ __html: opt.art }} />
        </div>
      ))}
    </div>
  );
}
