// Numeric parity vs Python's plot.py data collectors (_collect, _hemisphere).
// Fixtures under test/fixtures/{chart_data,sky_data}.json were generated by
// running the actual Python awadateki.design.design() (native nec2c) on
// line_none_circle_rhcp_2m.spec.json, then plot._collect()/_hemisphere() on
// the result -- see the generation notes in the PR description for the exact
// script. Only the DATA collectors are ported here (chartData/skyData); the
// SVG/HTML renderers in plot.py are a later UI-wave concern.

import { readFileSync } from "node:fs";
import { runNec } from "nec2c-wasm";
import { describe, expect, it } from "vitest";
import { design } from "../src/engine/design";
import { chartData, skyData } from "../src/engine/plot";
import { type DesignSpec, specFromDict } from "../src/engine/spec";

const GOLDENS = new URL("../goldens/", import.meta.url);
const FIXTURES = new URL("./fixtures/", import.meta.url);

function loadSpec(name: string): DesignSpec {
  return specFromDict(
    JSON.parse(readFileSync(new URL(`${name}.spec.json`, GOLDENS), "utf8")),
  );
}

function readFixtureJson(name: string): unknown {
  return JSON.parse(readFileSync(new URL(name, FIXTURES), "utf8"));
}

// Relative-tolerance numeric compare (matches golden.test.ts's convention).
function expectClose(actual: number, expected: number, path: string): void {
  const tol = 1e-9 * Math.max(Math.abs(expected), Math.abs(actual), 1e-9);
  expect(
    Math.abs(actual - expected),
    `${path}: |${actual} - ${expected}|`,
  ).toBeLessThanOrEqual(tol);
}

function expectPairsClose(
  actual: Array<[number, number]>,
  expected: [number, number][],
  path: string,
): void {
  expect(actual.length, `${path}: length`).toBe(expected.length);
  actual.forEach((pair, i) => {
    expectClose(pair[0], expected[i]?.[0] as number, `${path}[${i}][0]`);
    expectClose(pair[1], expected[i]?.[1] as number, `${path}[${i}][1]`);
  });
}

function expectBandClose(
  actual: [number, number] | null,
  expected: [number, number] | null,
  path: string,
): void {
  if (expected === null) {
    expect(actual, path).toBeNull();
    return;
  }
  expect(actual, `${path}: not null`).not.toBeNull();
  const a = actual as [number, number];
  expectClose(a[0], expected[0], `${path}[0]`);
  expectClose(a[1], expected[1], `${path}[1]`);
}

describe("chartData numeric parity", () => {
  it("matches Python's plot._collect for line_none_circle_rhcp_2m", async () => {
    const result = await design(loadSpec("line_none_circle_rhcp_2m"), runNec);
    const data = await chartData(result, runNec);
    const expected = readFixtureJson("chart_data.json") as {
      label: string;
      f0: number;
      z: { real: number; imag: number };
      sense: string;
      vswr_post: number;
      ar_cone: number;
      cov_gain: number;
      vswr_band: [number, number] | null;
      ar_band: [number, number] | null;
      vswr_freq: [number, number][];
      ar_freq: [number, number][];
      ar_elev: [number, number][];
      gain_elev: [number, number][];
    };

    expect(data.label).toBe(expected.label);
    expectClose(data.f0, expected.f0, "f0");
    expectClose(data.z.re, expected.z.real, "z.re");
    expectClose(data.z.im, expected.z.imag, "z.im");
    expect(data.sense).toBe(expected.sense);
    expectClose(data.vswrPost, expected.vswr_post, "vswrPost");
    expectClose(data.arCone, expected.ar_cone, "arCone");
    expectClose(data.covGain, expected.cov_gain, "covGain");
    expectBandClose(data.vswrBand, expected.vswr_band, "vswrBand");
    expectBandClose(data.arBand, expected.ar_band, "arBand");
    expectPairsClose(data.vswrFreq, expected.vswr_freq, "vswrFreq");
    expectPairsClose(data.arFreq, expected.ar_freq, "arFreq");
    expectPairsClose(data.arElev, expected.ar_elev, "arElev");
    expectPairsClose(data.gainElev, expected.gain_elev, "gainElev");
  });
});

describe("skyData numeric parity", () => {
  it("matches Python's plot._hemisphere for line_none_circle_rhcp_2m", async () => {
    const result = await design(loadSpec("line_none_circle_rhcp_2m"), runNec);
    const data = await skyData(result, runNec);
    const expected = readFixtureJson("sky_data.json") as {
      gain: Record<string, number>;
      ar: Record<string, number>;
      thetas: number[];
      phis: number[];
    };

    expect([...data.thetas]).toEqual(expected.thetas);
    expect([...data.phis]).toEqual(expected.phis);
    expect(data.gainMap.size).toBe(Object.keys(expected.gain).length);
    expect(data.arMap.size).toBe(Object.keys(expected.ar).length);
    for (const [key, value] of Object.entries(expected.gain)) {
      expectClose(data.gainMap.get(key) as number, value, `gainMap[${key}]`);
    }
    for (const [key, value] of Object.entries(expected.ar)) {
      expectClose(data.arMap.get(key) as number, value, `arMap[${key}]`);
    }
  });
});
