// Byte-identical parity vs Python's render_feed_schematic. Fixtures under
// test/fixtures/*.svg were generated by running the actual Python
// awadateki.design.design() (native nec2c) on the goldens' spec.json files,
// then awadateki.schematic.render_feed_schematic on the result -- see the
// generation notes in the PR description for the exact script. The two
// series-element fixtures (line_series_capacitor / line_series_inductor) are
// the line-normal result with z_in overridden (dataclasses.replace) to force
// a series capacitor or inductor, since none of the current goldens carry
// enough feedpoint reactance to trigger the series element on their own.

import { readFileSync } from "node:fs";
import { runNec } from "nec2c-wasm";
import { describe, expect, it } from "vitest";
import { type DesignResult, design } from "../src/engine/design";
import { renderFeedSchematic } from "../src/engine/schematic";
import { type DesignSpec, specFromDict } from "../src/engine/spec";

const GOLDENS = new URL("../goldens/", import.meta.url);
const FIXTURES = new URL("./fixtures/", import.meta.url);

function readGolden(name: string): string {
  return readFileSync(new URL(name, GOLDENS), "utf8");
}

function readFixture(name: string): string {
  return readFileSync(new URL(name, FIXTURES), "utf8");
}

function loadSpec(name: string): DesignSpec {
  return specFromDict(JSON.parse(readGolden(`${name}.spec.json`)));
}

describe("renderFeedSchematic byte parity", () => {
  it("line feed, normal connection", async () => {
    const result = await design(loadSpec("line_none_circle_rhcp_2m"), runNec);
    expect(renderFeedSchematic(result)).toBe(readFixture("line_normal.svg"));
  });

  it("line feed, crossed connection", async () => {
    const result = await design(loadSpec("line_none_circle_lhcp_2m"), runNec);
    expect(renderFeedSchematic(result)).toBe(readFixture("line_crossed.svg"));
  });

  it("balun4 feed, normal connection", async () => {
    const result = await design(loadSpec("balun4_none_circle_rhcp_2m"), runNec);
    expect(renderFeedSchematic(result)).toBe(readFixture("balun4_normal.svg"));
  });

  it("balun4 feed, crossed connection", async () => {
    const result = await design(loadSpec("balun4_none_circle_lhcp_2m"), runNec);
    expect(renderFeedSchematic(result)).toBe(readFixture("balun4_crossed.svg"));
  });

  it("choke feed, normal connection", async () => {
    const result = await design(loadSpec("choke_none_circle_rhcp_2m"), runNec);
    expect(renderFeedSchematic(result)).toBe(readFixture("choke_normal.svg"));
  });

  it("choke feed, crossed connection", async () => {
    const result = await design(loadSpec("choke_none_circle_lhcp_2m"), runNec);
    expect(renderFeedSchematic(result)).toBe(readFixture("choke_crossed.svg"));
  });

  it("line feed with a series capacitor (positive feedpoint reactance)", async () => {
    const base = await design(loadSpec("line_none_circle_rhcp_2m"), runNec);
    const result: DesignResult = {
      ...base,
      zIn: { re: base.zIn.re, im: 150.0 },
    };
    expect(renderFeedSchematic(result)).toBe(readFixture("line_series_capacitor.svg"));
  });

  it("line feed with a series inductor (negative feedpoint reactance)", async () => {
    const base = await design(loadSpec("line_none_circle_rhcp_2m"), runNec);
    const result: DesignResult = {
      ...base,
      zIn: { re: base.zIn.re, im: -150.0 },
    };
    expect(renderFeedSchematic(result)).toBe(readFixture("line_series_inductor.svg"));
  });
});
